mySOMEappV2/Models/User.cs
using System;
using System.Collections.Generic;

namespace mySOMEappV2.Models
{
    public partial class User
    {
        public User()
        {
            Comments = new HashSet<Comment>();
            FollowFollowerNavigations = new HashSet<Follow>();
            FollowFollowingNavigations = new HashSet<Follow>();
            MessageRecieverNavigations = new HashSet<Message>();
            MessageSenderNavigations = new HashSet<Message>();
            Posts = new HashSet<Post>();
        }

        public Guid Id { get; set; }
        public string FirstName { get; set; } = null!;
        public string LastName { get; set; } = null!;
        public string Email { get; set; } = null!;
        public string Password { get; set; } = null!;
        public DateTime? Birthday { get; set; }
        public byte[]? ProfilePic { get; set; }
        public byte[]? ProfileCover { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Follow> FollowFollowerNavigations { get; set; }
        public virtual ICollection<Follow> FollowFollowingNavigations { get; set; }
        public virtual ICollection<Message> MessageRecieverNavigations { get; set; }
        public virtual ICollection<Message> MessageSenderNavigations { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
    }
}

mySOMEappV2/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using mySOMEappV2.Authenticators;
using mySOMEappV2.Helpers;
using mySOMEappV2.Models;

namespace mySOMEappV2.Controllers
{
    public class UserController : Controller
    {
        private readonly someDBContext _context = new();

        // GET: UserController
        [HttpGet]
        public ActionResult Login() => View();

        [HttpPost]
        public IActionResult Login([FromForm] string Email, string Password)
        {
            var user = UserHelper.GetUser(Email, Password);
            if (user != null)
            {
                HttpContext.Session.SetString("loggedUser", user.FirstName + " " + user.LastName);
                HttpContext.Session.SetString("loggedUserId", user.Id.ToString());
                return RedirectToAction("Index", "Home");
            }
            return View(user);
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        // GET: UserController/Details/5
        public ActionResult Details(string name)
        {
            var userId = HttpContext.Session.GetString("loggedUserId");
            var user = UserHelper.GetDetails(name, userId);
            if (user != null)
            {
                ViewBag.UserId = user.Id.ToString();
                ViewBag.Messages = UserHelper.GetUserMessages(user);
                return View(user);
            }
            return View();
        }

        public ActionResult GetMessagesWith(string userId, string withUser)
        {
            var messages = UserHelper.GetMessagesWith(userId, withUser);
            ViewBag.UserId = userId;
            ViewBag.MsgRcvrId = withUser;
            return View(messages);
        }

        // GET: UserController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("FirstName, LastName, Email, Password, Birthday, ProfilePic, ProfileCover")] string FirstName, string LastName, string Username, string Email, string Password, DateTime Birthday, IFormFile ProfilePic, IFormFile ProfileCover)
        {
            var isValid = await UserHelper.CreateUser(FirstName, LastName, Email, Password, Birthday, ProfilePic, ProfileCover);

            if (isValid)
            {
                return RedirectToAction(nameof(Login));
            }
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> SendMessage(string senderId, string recieverId, string content)
        {
            await UserHelper.CreateMessage(senderId, recieverId, content);
            return RedirectToAction("GetMessagesWith", new { userId = senderId, withUser = recieverId });
        }


        public IActionResult AddFriend()
        {
            var users = _context.Users.ToList();
            return View(users);
        }


        [HttpPost]
        public async Task<IActionResult> AddFriend(string name)
        {
            var userId = HttpContext.Session.GetString("loggedUserId");
            var friendAdded = UserHelper.Follow(name, userId);
            if (friendAdded != null)
            {
                return RedirectToAction(nameof(AddFriend));
            }
            return RedirectToAction(nameof(AddFriend));
        }

        // GET: UserController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UserController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

mySOMEappV2/ViewComponents/PostCommentsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using mySOMEappV2.Helpers;

namespace mySOMEappV2.ViewComponents
{
    public class PostCommentsViewComponent : ViewComponent
    {

        public PostCommentsViewComponent()
        {
        }

        public async Task<IViewComponentResult> InvokeAsync(string postId, string userId, string userName)
        {
            var comments = HomeHelper.GetComments(postId);
            ViewBag.PostId = postId;
            ViewBag.UserId = userId;
            ViewBag.UserName = userName;
            return View(comments);
        }

    }
}

mySOMEappV2/Views/User/AddFriend.cshtml
@model IEnumerable<mySOMEappV2.Models.User>

@{
    ViewData["Title"] = "AddFriend";
}

<link rel="stylesheet" href="~/css/AddFriend.css" />

<form method="post" class="codehim-form">
    <div class="form-title">
        <div class="user-icon gr-bg">
            <i class="fa fa-user"></i>
        </div>
        <h2>Follow a friend</h2>
    </div>
    <label><i class="fa fa-envelope"></i>User's name:</label>
    <input name="name" class="cm-input" placeholder="User's name" list="@Model"/>
    <datalist id="@Model">
        @foreach (var person in Model)
        {
            <option value="@person.FirstName @person.LastName"/>
        }
    </datalist>
    <button type="submit" class="btn-login gr-bg">Follow</button>
</form>

mySOMEappV2/Views/User/Create.cshtml
@model mySOMEappV2.Models.User

@{
	ViewData["Title"] = "Create";
}

<link rel="stylesheet" href="/css/Create.css" />

<form asp-action="Create" enctype="multipart/form-data" class="codehim-form">
	<div class="form-title">
        <div class="user-icon gr-bg">
            <i class="fade fa-user"></i>
        </div>
        <h2>Sign up</h2>
    </div>
	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
	<div class="form-group">
		<label asp-for="FirstName" class="control-label fa fa-envelope"></label>
		<input asp-for="FirstName" class="form-control cm-input" />
		<span asp-validation-for="FirstName" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="LastName" class="control-label fa fa-envelope"></label>
		<input asp-for="LastName" class="form-control cm-input"/>
		<span asp-validation-for="LastName" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Email" class="control-label fa fa-envelope"></label>
		<input asp-for="Email" class="form-control cm-input" />
		<span asp-validation-for="Email" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Password" class="control-label fa fa-envelope"></label>
		<input asp-for="Password" type="password" class="form-control cm-input"/>
		<span asp-validation-for="Password" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Birthday" class="control-label fa fa-envelope"></label>
		<input asp-for="Birthday" type="date" class="form-control cm-input"/>
		<span asp-validation-for="Birthday" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="ProfilePic" class="control-label fa fa-envelope"></label>
		<input asp-for="ProfilePic" type="file" class="form-control cm-input" />
		<span asp-validation-for="ProfilePic" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="ProfileCover" class="control-label fa fa-envelope"></label>
		<input asp-for="ProfileCover" type="file" class="form-control cm-input" />
		<span asp-validation-for="ProfileCover" class="text-danger"></span>
	</div>
	<div class="form-group">
		<input type="submit" value="Create" class="btn btn-primary btn-login gr-bg" />
	</div>
</form>


<div style="margin-left: 32%;">
	<a>Back to @Html.ActionLink("Login", "Login")</a>
</div>

@section Scripts {
    @{
	await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

mySOMEappV2/Views/User/Details.cshtml
@model mySOMEappV2.Models.User

@{
    ViewData["Title"] = "User Page";
    var Messages = ViewBag.Messages;
    var userId = ViewBag.UserId;
}

<link rel="stylesheet" href="~/css/Details.css" />

@if (Model == null)
{


    <div>
        404: User not found
    </div> }
else
{

    <div class="main">
        <div class="profcov">
            <img src="data:Model.ProfileCover/jpg;base64,@Convert.ToBase64String(Model.ProfileCover)" />
        </div>
        <div class="profpic">
            <img src="data:Model.ProfilePic/jpg;base64,@Convert.ToBase64String(Model.ProfilePic)" />
        </div>
    </div>

    <div class="container">
        <div class="con-child">
            <form method="post" enctype="multipart/form-data" class="codehim-form">
                <input type="button" onclick="openForm()" value="Post" class="btn-post gr-bg" />
            </form>

            <div class="form-popup" id="myForm">
                <form asp-action="Index" class="form-container codehim-form" enctype="multipart/form-data">
                    <h1 style="text-align:center;">Create a Post</h1>

                    <hr />

                    <textarea type="text" name="postContent" placeholder="What's on your mind?" class="cm-input cm-pc-input"></textarea>

                    <div class="file-upload">
                        <button class="file-upload-btn gr-bg" type="button" onclick="$('.file-upload-input').trigger( 'click' )">Add Image</button>

                        <div class="image-upload-wrap">
                            <input class="file-upload-input" type='file' name="file" onchange="readURL(this);" />
                            <div class="drag-text">
                                <h3>Drag and drop a file or select add Image</h3>
                            </div>
                        </div>
                        <div class="file-upload-content">
                            <img class="file-upload-image" src="#" alt="your image" />
                            <div class="image-title-wrap">
                                <button type="button" onclick="removeUpload()" class="remove-image">Remove <span class="image-title">Uploaded Image</span></button>
                            </div>
                        </div>
                    </div>

                    <button type="submit" class="btn-post gr-bg">Post</button>
                    <input type="button" class="btn-post gr-cl" onclick="closeForm()" value="Close" />
                </form>
            </div>

            <div class="grid-posts-container">
                @{ foreach (var post in Model.Posts)
                    {
                        <div class="grid-post-item">
                            <h5 class="poster">@Model.FirstName @Model.LastName</h5>
                            <h6 class="post-timing">@post.Time</h6>
                            <p class="post-content">@post.Content</p>
                            @if (post.Media != null)
                            {
                                <img class="post-media" src="data:@post.Media/jpg;base64,@Convert.ToBase64String(post.Media)" />
                            }
                            @if (post.Likes != 0)
                            {
                                <p class="post-likes">@post.Likes person likes this post</p>
                            }
                            @using (Html.BeginForm("LikePost", "Home", new { postId = post.Id.ToString() }, FormMethod.Post))
                            {
                                <input type="submit" value="Like" class="btn-like-post gr-bg" />
                            }
                            <input type="button" value="Comment" class="btn-like-post gr-bg" onclick="showComments(@post.Id.ToString())" />

                            <div class="comments-popup" id="@post.Id.ToString()">
                                @await Component.InvokeAsync("PostComments", new { postId = post.Id.ToString(), userId = userId })
                            </div>
                        </div>

                    }
                }
            </div>

        </div>
        <div class="con-child">
            <form class="codehim-messages">
                <input type="button" value="Messages" class="btn-msg gr-bg" onclick="showMessages()" />
            </form>
            <div class="messages-popup" id="myMessages">
                <div class="grid-msg-container">
                    @foreach (var messagewith in Messages)
                    {
                        <div class="grid-msg-item">
                            <a class="msg-sndr-rcvr" asp-controller="User" asp-action="GetMessagesWith" asp-route-withUser="@messagewith.UserId" asp-route-userId="@userId">@messagewith.FirstName @messagewith.LastName</a>
                        </div>
                    }
                </div>
                <form class="form-message" asp-action="SendMessage" method="get">
                    <input type="submit" value="Send A Message" class="btn-msg gr-bg" />
                </form>

            </div>
        </div>
    </div>
}
<script>

    function openForm() {
        document.getElementById("myForm").style.display = "block";
    }

    function closeForm() {
        document.getElementById("myForm").style.display = "none";
    }

    function showComments(postId) {
        document.getElementById(postId).style.display = "block";
    }

    function hideComments(postId) {
        document.getElementById(postId).style.display = "none";
    }

    function showMessages() {
        document.getElementById("myMessages").style.display = "block";
    }

    function closeMessages() {
        document.getElementById("myMessages").style.display = "none";
    }

    function readURL(input) {
        if (input.files && input.files[0]) {

            var reader = new FileReader();

            reader.onload = function (e) {
                $('.image-upload-wrap').hide();

                $('.file-upload-image').attr('src', e.target.result);
                $('.file-upload-content').show();

                $('.image-title').html(input.files[0].name);
            };

            reader.readAsDataURL(input.files[0]);

        } else {
            removeUpload();
        }
    }

    function removeUpload() {
        $('.file-upload-input').replaceWith($('.file-upload-input').clone());
        $('.file-upload-content').hide();
        $('.image-upload-wrap').show();
    }
    $('.image-upload-wrap').bind('dragover', function () {
        $('.image-upload-wrap').addClass('image-dropping');
    });
    $('.image-upload-wrap').bind('dragleave', function () {
        $('.image-upload-wrap').removeClass('image-dropping');
    });


    Resources
</script>
<script class="jsbin" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>

mySOMEappV2/Views/User/GetMessagesWithcshtml.cshtml
@model IEnumerable<mySOMEappV2.Models.Message>
@{
    ViewData["Title"] = "Messages";
    var userId = ViewBag.UserId;
    var msgRcvrId = ViewBag.MsgRcvrId;
}

<link href="~/css/MessagesWith.css" rel="stylesheet" />

<div class="codehim-form">
    <div class="grid-messages-container">
        <h1>Chat</h1>

        <hr />

        @foreach (var msg in Model)
        {
            if (msg.Sender == userId)
            {
                <div class="grid-myMessage-item">
                    <p class="msg-content">@msg.Content</p>
                </div>
            }
            else
            {
                <div class="grid-message-item">
                    <p class="msg-sender">@msg.SenderNavigation.FirstName @msg.SenderNavigation.LastName</p>
                    <p class="msg-content">@msg.Content</p>
                </div>
            }
        }
    </div>
    <form asp-controller="User"
          asp-action="SendMessage"
          method="post">

        <input type="text" name="content" placeholder="Enter a message" class="ct-input" />
        <input type="number" name="senderId" value="@userId" hidden />
        <input type="number" name="recieverId" value="@msgRcvrId" hidden />
        <input type="submit" value="Send" class="btn-send-msg gr-bg" />
    </form>
</div>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-ajax-unobtrusive@3.2.6/dist/jquery.unobtrusive-ajax.min.js"></script>
}

mySOMEappV2/Views/User/Login.cshtml
@model mySOMEappV2.Models.User

@{
	ViewData["Title"] = "Login";
}

<link rel="stylesheet" href="~/css/Login.css" />


<form asp-action="Login" class="codehim-form">
	<div class="form-title">
		<div class="user-icon gr-bg">
			<i class="fa fa-user"></i>
		</div>
		<h2>Login</h2>
	</div>
	<div class="form-group">
		<label asp-for="Email"><i class="fa fa-envelope"></i>Email:</label>
		<input asp-for="Email" type="email" class="cm-input" />
		<span asp-validation-for="Email" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Password"><i class="fa fa-lock"></i>Password:</label>
		<input asp-for="Password" type="password" class="cm-input" />
		<span asp-validation-for="Password" class="text-danger"></span>
	</div>
	<div class="form-group">
		<input type="submit" value="Login" class="btn btn-primary" />
	</div>
</form>

<div style="margin-left: 32%;">
	<a>You don't have an account? Sign up @Html.ActionLink("Here", "Create")</a>
</div>

@section Scripts {
    @{
	await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}